CREATE TABLE items (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    item_name VARCHAR(50) NOT NULL,
    item_desc TEXT NOT NULL DEFAULT ''
);

CREATE TABLE sales (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    item_id INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
    sale_value INTEGER NOT NULL,
    ts TIMESTAMP NOT NULL DEFAULT current_timestamp
);